# Generated by Django 5.2.5 on 2025-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='total_downloads',
            field=models.PositiveIntegerField(default=0, help_text='Total number of photos downloaded by the customer'),
        ),
    ]
