# Generated by Django 4.2.7 on 2025-09-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "customer_dashboard",
            "0003_alter_customerprofile_options_alter_favorite_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="customer_da_content_a39b52_idx",
            old_name="customer_da_content_09c7c0_idx",
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Content type of the related object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
    ]
