# Generated by Django 4.2.7 on 2025-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="A short biography or description about the user",
                null=True,
                verbose_name="bio",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's contact phone number",
                max_length=20,
                null=True,
                verbose_name="phone number",
            ),
        ),
    ]
