# Generated by Django 4.2.7 on 2025-09-12 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_bio_customuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Enable all email notifications",
                        verbose_name="email notifications",
                    ),
                ),
                (
                    "new_gallery_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive emails when new galleries are added",
                        verbose_name="new gallery notifications",
                    ),
                ),
                (
                    "event_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Receive emails about event updates",
                        verbose_name="event updates",
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive promotional emails and offers",
                        verbose_name="marketing emails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
    ]
