# Generated by Django 5.2.5 on 2025-09-27 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='verification_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qrcodes/'),
        ),
    ]
