# Generated by Django 5.2.5 on 2025-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpurchase_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
    ]
