# Generated by Django 5.2.5 on 2025-09-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_remove_eventregistration_event_ticket_and_more'),
        ('tickets', '0003_ticketpurchase_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='event_ticket',
            field=models.ForeignKey(db_column='ticket_type_id', default=1, help_text='The event-specific ticket that was purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='gallery.eventticket', verbose_name='event ticket'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
