# Generated by Django 4.2.7 on 2025-09-07 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public - Anyone can view"),
                            ("private", "Private - Requires PIN to view"),
                        ],
                        default="public",
                        help_text="Control who can view this event's galleries",
                        max_length=10,
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        help_text="PIN code for private events (auto-generated for private events)",
                        max_length=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event this gallery belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="gallery.event",
            ),
        ),
    ]
