# Generated by Django 4.2.7 on 2025-09-07 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_event_gallery_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date", "name"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="pin",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="PIN code for private events (auto-generated for private events)",
                max_length=6,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EventCoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=gallery.models.EventCoverImage.get_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this will be the default cover image for the event",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which the cover images should be displayed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this cover image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covers",
                        to="gallery.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Cover Image",
                "verbose_name_plural": "Event Cover Images",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
