# Generated by Django 4.2.7 on 2025-09-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0003_alter_event_options_alter_event_pin_eventcoverimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount paid in USD", max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment processor's transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used (e.g., 'card', 'paypal')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="download",
            name="download_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique token for secure download links",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_purchasable",
            field=models.BooleanField(
                default=True,
                help_text="If True, this photo can be purchased separately",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price in USD for downloading this photo. 0 means free.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["download_token"], name="gallery_dow_downloa_4a72db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["user", "photo"], name="gallery_dow_user_id_60c891_idx"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment associated with this download, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downloads",
                to="gallery.payment",
            ),
        ),
    ]
