# Generated by Django 4.2.7 on 2025-09-07 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "gallery",
            "0004_payment_download_download_token_photo_is_purchasable_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded this photo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
