# Generated by Django 4.2.7 on 2025-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_photo_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="featured_until",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, the gallery will be featured until this date",
                null=True,
            ),
        ),
    ]
