# Generated by Django 5.2.5 on 2025-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_gallery_featured_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, help_text='If True, gallery is visible to everyone. If False, only accessible via direct link.'),
        ),
    ]
