# Generated by Django 5.2.5 on 2025-09-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_like_remove_download_gallery_dow_downloa_4a72db_idx_and_more'),
    ]

    operations = [
    ]
