# Generated by Django 5.2.5 on 2025-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_add_ticket_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text='Maximum number of attendees (for RSVP/paid events)'
            ),
        ),
    ]
