# Generated by Django 5.2.5 on 2025-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_add_max_attendees_to_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day events', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='has_tickets',
            field=models.BooleanField(default=False, help_text='Check if this event requires tickets'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('free', 'Free - No ticket required'), ('paid', 'Paid - Requires ticket purchase'), ('rsvp', 'RSVP - Free but requires registration')], default='free', help_text='Type of ticketing for this event', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='like_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes for this photo'),
        ),
    ]
