# Generated by Django 5.2.5 on 2025-09-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_update_eventregistration_ticket'),
        ('gallery', '0013_ticketgroup_ticketlevel_tickettype_eventticket'),
    ]

    operations = [
    ]
