# Generated by Django 5.2.5 on 2025-09-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_merge_20250926_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event_ticket',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='gallery.ticket'),
        ),
    ]
