# Generated by Django 5.2.5 on 2025-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_remove_eventregistration_event_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('KES', 'Kenyan Shilling (KSh)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('ZAR', 'South African Rand (R)'), ('INR', 'Indian Rupee (₹)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)')], default='USD', help_text="Currency for this event's ticket prices", max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('KES', 'Kenyan Shilling (KSh)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('ZAR', 'South African Rand (R)'), ('INR', 'Indian Rupee (₹)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)')], default='USD', help_text="Currency for this ticket. Defaults to the event's currency.", max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in the selected currency. Set to 0 for free tickets.', max_digits=10),
        ),
    ]
