# Generated by Django 5.2.5 on 2025-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_add_currency_to_events_and_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('KES', 'Kenyan Shilling (KSh)'), ('UGX', 'Ugandan Shilling (USh)'), ('TZS', 'Tanzanian Shilling (TSh)')], default='USD', help_text='Currency for this ticket price', max_length=3),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in the selected currency', max_digits=10),
        ),
    ]
