# Generated by Django 5.2.5 on 2025-10-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_enhance_eventregistration'),
        ('gallery', '0017_eventticket_currency_alter_eventticket_price'),
    ]

    operations = [
    ]
