# Generated by Django 5.2.5 on 2025-10-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_merge_20251002_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='quantity',
        ),
    ]
