# Generated by Django 5.2.5 on 2025-10-04 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_remove_eventregistration_is_paid_and_more'),
        ('payments', '0004_remove_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='payments.order'),
        ),
    ]
