# Generated by Django 4.2.7 on 2025-09-08 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("country_code", models.CharField(default="+254", max_length=5)),
                ("message", models.TextField()),
                (
                    "subject",
                    models.CharField(default="Bulk Download Inquiry", max_length=255),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
