# Generated by Django 4.2.7 on 2025-09-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="country_code",
            field=models.CharField(default="+254", max_length=10),
        ),
    ]
