# Generated by Django 4.2.7 on 2025-09-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0002_alter_contactsubmission_country_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactsubmission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
            },
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="response_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("responded", "Responded"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
    ]
