# Generated by Django 4.2.7 on 2025-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_contactsubmission_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="subject",
            field=models.CharField(default="User Inquiry", max_length=255),
        ),
    ]
