# Generated by Django 5.2.5 on 2025-09-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False, help_text='Use live mode for real transactions. Uncheck for test mode.', verbose_name='Live Mode')),
                ('test_secret_key', models.CharField(blank=True, help_text='Your Paystack test secret key', max_length=255, verbose_name='Test Secret Key')),
                ('test_public_key', models.CharField(blank=True, help_text='Your Paystack test public key', max_length=255, verbose_name='Test Public Key')),
                ('live_secret_key', models.CharField(blank=True, help_text='Your Paystack live secret key', max_length=255, verbose_name='Live Secret Key')),
                ('live_public_key', models.CharField(blank=True, help_text='Your Paystack live public key', max_length=255, verbose_name='Live Public Key')),
                ('webhook_secret', models.CharField(blank=True, help_text='Your Paystack webhook secret for verifying webhook events', max_length=255, verbose_name='Webhook Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paystack Configuration',
                'verbose_name_plural': 'Paystack Configuration',
            },
        ),
        migrations.AlterUniqueTogether(
            name='downloadtoken',
            unique_together=set(),
        ),
    ]
