# Generated by Django 5.2.5 on 2025-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paystackconfig_alter_downloadtoken_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
