# Generated by Django 5.2.5 on 2025-10-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_charge_id',
        ),
    ]
