# Generated by Django 4.2.7 on 2025-09-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
